### ISSUE TITLE
Tive um problema

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#1]
Quero que vocês corrijam por favor.

**Comment by silmargeremia** [comment]
YES SIR o>

**Comment by Odilhao** [comment]
Serio isso um teste?

**Comment by diegofrutuoso** [comment]
É um teste sim Odilon. Vamos mudar a plataforma de report de bugs e melhorias para o github.
Pra ver se facilita do pessoal mandar coisas pra gente e irmos controlando o que aparece.

**Comment by Odilhao** [comment]
Faz bastante sentido, se o github ficar ruim na parte de report, nós poderíamos migrar tudo para o gitlab.

**Comment by Odilhao** [comment]
**BUG**

O bom dessa bug tracker é o suporte a MD.

- [Bugs](#Bugs)
- * [Bug1](#Bug1)
- * [Bug2](#Bug2)




























<a id="Bug1"></a>

**BUG 1**

![](https://www.bugs.com/images/pest-library/other-bugs.png)

<a id="Bug2"></a>

**BUG2**
![](http://sdtimes.com/wp-content/uploads/2016/09/0927.sdt-springfield.png)
Esse é o bug padrão
