### ISSUE TITLE
Não consigo confirmar email

### ISSUE THREAD

**Issue by Guardioesdacomedia** [CloudRadioProject/BugReport#103]
Eu fiz o cadastro e só faltava confirmar o email para finalizar a conta, mas quando eu clico no link para confirmar a conta aparece que a página não foi encontrada. Espero que consertem isso

**Comment by AlanBessa** [comment]
Reenviei um outro email de confirmação. Por favor tente denovo

**Comment by Guardioesdacomedia** [comment]
Aconteceu a mesma coisa aparece o erro 404 not found

2017-03-11 15:48 GMT-03:00 AlanBessa <notifications@github.com>:

**Comment by AlanBessa** [comment]
Por favor, se puder compartilhar fotos ou videos do problema, ajudará mais na investigação do erro.

**Comment by Guardioesdacomedia** [comment]
A página já apareceu, obrigado pela ajuda

2017-03-12 19:36 GMT-03:00 AlanBessa <notifications@github.com>:

**Comment by diegofrutuoso** [comment]
Obrigado pelas observações.

Qualquer problema adicional com confirmação de e-mail sinta-se a vontade para reabrir a issue.
