### ISSUE TITLE
Importação 404

### ISSUE THREAD

**Issue by FlynnsArcade** [CloudRadioProject/BugReport#104]
Recebi o e-mail para importar os episódios de meu podcast para o Cloud Radio, porém o link vai para uma página 404.

**Comment by AlanBessa** [comment]
Por favor, se puder compartilhar fotos ou videos do problema, ajudará mais na investigação do erro.

**Comment by FlynnsArcade** [comment]
![sem titulo-1](https://cloud.githubusercontent.com/assets/26366358/23839214/35de01e8-077b-11e7-8dc3-bee4d43c4536.jpg)

Quando clico no link enviado pro meu e-mail para importar os episódios ele abre essa pagina de erro.

**Comment by diegofrutuoso** [comment]
Bom dia. O problema foi corrigido. Muito obrigado pela observação.

Qualquer problema sinta-se a vontade para reabrir o issue.
