### ISSUE TITLE
Adicionar botão de "Adicionar a playlist" na home

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#11]
Sugestão, colocar uma botão de add a playlist logo a baixo do nome do episódio, ajudaria muito a montar um playlist mais rapida, ou seja, não seria necessario abrir todos as paginas de episódio que deseja adicionar.

=================================================

Somente após a inclusão das playlists, será habilitado um botão nos objetos da home, assim como existe com o Youtube hoje.

**Comment by lczanatta** [comment]
Adicionado, mas só será liberado quando a integração com o player for implementada
