### ISSUE TITLE
Não tem dados de OpenGraph

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#12]
Ao compartilhar no facebook/redes sociais, o link não fica bonitinho.

Isso porque não tem as tags de opengraph.

=============================================

Link com exemplos de como fazer:

http://tableless.com.br/utilizando-meta-tags-facebook/

**Comment by diegofrutuoso** [comment]
Deve ser feito nas páginas de:

Home
Episódio
Estação

**Comment by diegofrutuoso** [comment]
Implementado para Facebook e Twitter

**Comment by Odilhao** [comment]
Agora o opengraph funciona com:
Facebook
Twitter
Pinterest
Google
Skype
WhatsApp(Parcialmente)
Telegram
