### ISSUE TITLE
Clicar em um link te tira do site

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#14]
Ao clicar em algum link, a pagina é direcionada para o link. Como sugestão seria melhor abrir uma nova aba ou pagina no navegador.

**Comment by lczanatta** [comment]
Essa questão é mais de configuração de quem faz a descrição do episódio/Estação.
Como fazer para os links serem configurados para abrir uma nova pagina:
Gere o texto do Link:
![image](https://cloud.githubusercontent.com/assets/13223895/21439528/bd2d829e-c875-11e6-87ed-5f7a368d7ac5.png)
Selecione o link:
![image](https://cloud.githubusercontent.com/assets/13223895/21439560/e8fcd064-c875-11e6-9874-b85016492e78.png)
Depois click no botão para adicionar o link ao texto selecionado:
![image](https://cloud.githubusercontent.com/assets/13223895/21439584/05b29be4-c876-11e6-938e-7818d79e097a.png)
O sistema vai abrir uma caixa de dialogo para você inserir o link:
![image](https://cloud.githubusercontent.com/assets/13223895/21439622/27c25bca-c876-11e6-97af-be156f9245c7.png)
Após apertar ok: e depois selecione o link na caixa de edição:
![image](https://cloud.githubusercontent.com/assets/13223895/21439652/692a6486-c876-11e6-94e2-446cc3bbc31c.png)
E aperte nesse botão para que o link possa abrir uma nova tela:
![image](https://cloud.githubusercontent.com/assets/13223895/21439683/92220b32-c876-11e6-95fc-502b6724bc7c.png)

Obrigado pelo seu feedback

**Comment by lczanatta** [comment]
@diegofrutuoso Verificar a possibilidade de se colocar a propriedade 'target="_blank"' nos links que vem por exportação de feed!

**Comment by diegofrutuoso** [comment]
Adicionado à fila do back-end.
Obrigado @lczanatta

**Comment by diegofrutuoso** [comment]
Corrigido. Prosseguirá para testes.
