### ISSUE TITLE
Quando os nomes dos episódios são longos eles não aparecem na prévia

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#15]
Quando os nomes dos episódios são longos eles não aparecem na prévia.

===================================================

Quando passar o mouse por cima do nome, mostrar num tooltip o nome completo.

**Comment by lczanatta** [comment]
Adicionado Tooltip com o nome completo. Agora basta passar o mouse por cima do nome, que aparecera um "caixa" com o nome completo.
