### ISSUE TITLE
Foto do Perfil

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#17]
Na configuração do perfil, a foto que eu tentei utilizar deu como carregada, mas não aparece imagem nenhuma.

==============================

Rever minificação e adicionar suporte ao formato jpeg além do jpg

**Comment by lczanatta** [comment]
@diegofrutuoso isso já não foi feito? testei com jpg e jpeg e funcionou? verificar qual foi o formato que ele usou!

**Comment by lczanatta** [comment]
Foi feito o teste e o problemas não existe mais.
