### ISSUE TITLE
Mensagem de erro não explica o problema - Upload de imagem

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#18]
Ao tentar inserir uma foto no me perfil ocorre erro "Falha na Requisição
Sua requisição não pode ser processada. Erros: undefined" ao clicar em SALVAR.

==========================================

Melhorar mensagem de erro

**Comment by lczanatta** [comment]
Ajustado para quando a pessoa tenta adicionar imagem de extensão não suportada
