### ISSUE TITLE
Problemas no campo descrição - Firefox

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#19]
No campo "descrição", fui tentar preencher e não consegui. Apertei nos botões h1, h2, além de mais alguns que estava logo acima do campo, e o campo simplesmente sumiu.

=====================

Observação - No perfil/redirect

**Comment by AlanBessa** [comment]
Testado e não vi nenhum problema. Tem como obter mais informação do pessoal que averiguou este problema?

**Comment by AlanBessa** [comment]
Plugin Atualizado, deve ficar de observação.
