### ISSUE TITLE
Listas de País/Cidade/Estado

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#2]
Dropbox de inserção de país não funcional, não permite salvar os detalhes, nem selecionar cidade e estado.

============================

Foi solicitada a inserção também de mais países, estados e cidades e a revisão do plugin, que fica lento em dispositivos mobile e no  navegador  Edge.

**Comment by edsondaniel9** [comment]
Voltei a ter o mesmo problema relatado acima para informar o pais, estou utilizando o navegador Chrome (Version 55.0.2883.87 m (64-bit)) no Windows 10 (64-bit)

**Comment by AlanBessa** [comment]
Que problema vc teve para relatar pais se há somente um no momento?

2017-01-17 14:24 GMT-02:00 edsondaniel9 <notifications@github.com>:

**Comment by edsondaniel9** [comment]
Mesmo clicando no campo não apareceu opção de selecionar um pais, tentei escrever manualmente "Brasil", ou iniciar a escrita com B e não apareceu para selecionar nenhum pais
