### ISSUE TITLE
Poder curtir o cast que esta sendo escutado mesmo estando em outras paginas.

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#21]
Poder curtir o cast que esta sendo escutado mesmo estando em outras paginas.

**Comment by diegofrutuoso** [comment]
@lczanatta Creio que somente com inclusão do ícone e aproveitando os outros códigos de curtir conseguimos esse efeito.

**Comment by lczanatta** [comment]
Ajuste realizado. agora o usuário logado pode curtir diretamente no player
