### ISSUE TITLE
Player pausa quando clico em assinar estação

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#22]
eu estava ouvindo café brasil e continuei navegando e procurando outros podcasts para assinar, quando cliquei em assinar outro ele parou tudo que eu estava ouvindo e voltou pro começo.

=================================

Ainda não conseguimos reproduzir, precisamos investigar mais a fundo.

**Comment by diegofrutuoso** [comment]
@lczanatta Pode investigar mais uma vez por favor?
Caso o cenário não se reproduza mais pode fechar.
Obrigado

**Comment by lczanatta** [comment]
@diegofrutuoso não consegui reproduzir o erro. Nem no firefox e nem no chrome. Talvez na época o assinar podia estar com algum erro. Assim ocasionou o áudio parar.
