### ISSUE TITLE
Modificações Organizacionais/Estéticas: Página da Estação

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#28]
- Onde não houver dado, remove ro campo. Exemplo: Telefone/Whatsapp:  -
- Colocar todos os botões com o mesmo tamanho na listagem de episódios (imagem anexa)
![1](https://cloud.githubusercontent.com/assets/18125774/21188338/330420f6-c202-11e6-8743-d8274cf939cc.png)
- Colocar o botão editar no final dos botões (último)
- Adicionar mais um botão “Compartilhar” junto aos demais (abre opções para compartilhar Facebook e Twitter)
- Mudar a quantidade de episódios listados para 10 por página.

**Comment by AlanBessa** [comment]
Concluido sem Compartilhamento (redirecionado para #46)

**Comment by silmargeremia** [comment]
Falta botão de compartilhamento

**Comment by lczanatta** [comment]
A melhoria para adicionar o compartilhamento foi transferida para a  [issue 101](https://github.com/CloudRadioProject/BugReport/issues/101)
