### ISSUE TITLE
Modificações Organizacionais/Estéticas: Página do Episódio

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#29]
- Deixar os botões todos com o mesmo tamanho
- Acrescentar botão de compartilhar
- Mudar o comportamento do curtir. Deixar o curtir com a mesma cor dos outros botões e pintar de verde quando a pessoa curtir. Abandonar o sinal de negativo.
- Aumentar o tamanho da arte do episódio para 2x o atual.
- Colocar um snippet (dica) no botão de adicionar a playlist (ver como funciona com multiplas playlists, provavelmente vai precisar abrir uma caixa suspensa com as playlists pro usuário selecionar).

**Comment by lczanatta** [comment]
Ajustes realizados. 
Menos o compartilhar episódio.

**Comment by lczanatta** [comment]
A melhoria para adicionar o compartilhamento foi transferida para a issue 101
