### ISSUE TITLE
Modificações Organizacionais/Estéticas: Página Inscrições

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#32]
- Aplicar a listagem dos episódios da estação a mesma regra de espaçamento da página Popular:
![1](https://cloud.githubusercontent.com/assets/18125774/21188722/6eade1f4-c203-11e6-8e28-9f4a9d7ae9ec.png)
- listar duas linhas por estação
- listar máximo de 5 estações por página
- ao passar o mouse sobre um episódio, mostrar dois botões: Play e +, respectivamente “tocar” e “adicionar à playlist”  (ver como funciona com multiplas playlists, provavelmente vai precisar abrir uma caixa suspensa com as playlists pro usuário selecionar).
- listar duas linhas de “pessoas que você segue”

**Comment by lczanatta** [comment]
modificações:
- [x] duas linhas de episódios por estação

- [x] 5 estações por página

- [x] Botão de playlist com caixa suspensa

- [x] duas linhas de pessoas que você segue
