### ISSUE TITLE
Modificações Organizacionais/Estéticas: Página Recentes

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#33]
- Aplicar a listagem de estações e episódios a mesma regra de espaçamento da página Popular:
![1](https://cloud.githubusercontent.com/assets/18125774/21188789/a7f936e8-c203-11e6-9bb7-a02966c3b9ef.png)
- listar duas linhas de estações
- listar duas linhas de episódios
- adicionar um campo: ‘Pessoas mais ativas” e listar as 10 pessoas mais ativas atualmente (com mais publicações ou referencias)
- ao passar o mouse sobre um episódio recente, mostrar dois botões: Play e +, respectivamente “tocar” e “adicionar à playlist”  (ver como funciona com multiplas playlists, provavelmente vai precisar abrir uma caixa suspensa com as playlists pro usuário selecionar).

**Comment by lczanatta** [comment]
modificação feita, para as listas de episódio e estações.
