### ISSUE TITLE
Modificações Organizacionais/Estéticas: Página Todas as Estações

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#34]
Aplicar a listagem de estações a mesma regra de espaçamento da página Popular
![1](https://cloud.githubusercontent.com/assets/18125774/21188834/cb68dc78-c203-11e6-8b9f-ebae7fc2c985.png)

**Comment by lczanatta** [comment]
Espaçamento entre as estações foi ajustada
