### ISSUE TITLE
Perda de sincronismo do player com o audio

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#38]
Alguns usuários estão reportando que não conseguem pausar, parar o audio.
Isso pode ser possível por ter perdido referência ao arquivo de audio, dessa forma as rotinas não atuam sobre o arquivo que está efetivamente rodando

**Comment by felipeprov** [comment]
Reproduzido, play duas vezes bem rápido pode criar um audio fantasma que o usuário não tem controle... 
Investigando...

**Comment by felipeprov** [comment]
Resolvi algumas brechas que poderiam causar o problema:
- lentidão ao iniciar o streaming
- múltiplos toques no botão play.
Fiz algumas melhorias internas, e adicionei uma tela bloqueando a interação enquanto o streaming é estabelecido.
