### ISSUE TITLE
Usuários reclamando que não conseguem adicionar nada a playlist

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#42]
Entender melhor o que está acontecendo.
Bug, ou problema de feedback de onde as coisas estão indo?

**Comment by felipeprov** [comment]
Tentei reproduzir o problema e não consegui, estou finalizando por não conseguir reproduzir
@diegofrutuoso

**Comment by diegofrutuoso** [comment]
Perfeito, obrigado @felipeprov
