### ISSUE TITLE
Problemas com Streaming

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#43]
Quando clica em play via streaming, ele adiciona na lista de streaming.
Fazer ele sempre reproduzir, independente de estar reproduzindo outro, play sempre dá play.
Somente o "+" adiciona a playlist.

**Comment by felipeprov** [comment]
Problema resolvido, o + adiciona na lista e dá um play.  o + apenas adiciona na lista
Isso é necessário pois internamente sempre é necessário existir uma playlist relacionada a uma execução.
