### ISSUE TITLE
Sincronizar dados de reprodução sempre que possível

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#44]
Alterar comportamento para que a cada 5 minutos, caso tenham pendências de sincronia, o aplicativo envie os dados de reprodução que já possui, para que sempre tenhamos os dados sincronizados o mais próximo da realidade.
Em todos os cenários de conectividade.

**Comment by felipeprov** [comment]
Isso deveria funcionar no wifi, e no 3G sob configuração.
Hoje a sincronização é feita em momentos que o audio para, seja no pause ou no stop.
Tudo que pode gerar custos pro usuário tem que ser configurável

**Comment by diegofrutuoso** [comment]
Issue consertada, está sincronizando a contento.
Vou fechar ela, qualquer problema reabrimos.
