### ISSUE TITLE
Problemas ao sair do aplicativo e travar o celular

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#45]
No Moto G3, ao dar play em um episódio baixado, sair do aplicativo e travar o celular, o episódio para de reproduzir. Se eu travar o celular sem sair do app ele funciona normal.

Várias tentativas, sempre ocorrendo nesse mesmo padrão.
Play -> Home -> Lock -> Aplicativo encerra sozinho.

**Comment by felipeprov** [comment]
Mais um problema relativo a forma que o audio era anteriormente tratado, agora temos um serviço dedicado ao player, devemos passar a ver menos problemas relativos a reproduções parando inesperadamente.
