### ISSUE TITLE
Playlist sempre visivel

### ISSUE THREAD

**Issue by gabrieltulli** [CloudRadioProject/BugReport#47]
Atualmente a playlist de reprodução só aparece se existe um podcast sendo tocado. 
Para continuar a reprodução de um podcast previamente interrompido (#amigosDoPause) é necessário que o usuário entre na opção "histórico" e mande tocar o podcast novamente.
Esta melhoria teria como objetivo, facilitar a retomada de um podcast interrompido.

**Comment by diegofrutuoso** [comment]
Olá Gabriel.

Está sendo implementada uma playlist mais sofisticada, já deve aparecer nas próximas releases do site.
Te mantenho informado. :)

**Comment by silmargeremia** [comment]
Diego, você precisa responder diretamente no sistema de bug do git ou ele
não recebe o feedback

**Comment by lczanatta** [comment]
Fechando essa issue pois todas questões envolvendo playlist vai ser acompanhada pela [Issue 23](https://github.com/CloudRadioProject/BugReport/issues/23)
