### ISSUE TITLE
Tela/Visão de podcasts recentes

### ISSUE THREAD

**Issue by gabrieltulli** [CloudRadioProject/BugReport#48]
Disponibilizar uma página com os podcasts mais recentes das estações que eu assino.
Seria algo muito similar a tela de [inscrições do youtube](https://www.youtube.com/feed/subscriptions)

**Comment by AlanBessa** [comment]
Isso já existe dentro do nosso sistema. É a aba inscrição. Lá você encontra todas as estações na qual você está inscrito, organizado de forma alfabética, cuja cada estação contêm os últimos 5 episódios publicados nela. Confere lá!

**Comment by gabrieltulli** [comment]
@AlanBessa , conheço a tela que existe. Mas não acho que ela seja "fácil de usar", por exemplo:
depois de 4 dias sem entrar no cloudradio, quero ver todos os novos podcasts publicados para as minhas inscrições. hoje eu teria que passar estação por estação e ver qual a novidade.

Olhando melhor, acredito que seria a aba recentes só que somente das minhas inscrições.

**Comment by silmargeremia** [comment]
Isso está sendo desenvolvido Gabriel, um recurso com a listagem de
atualizações, assim como para guardar as suas playlists.
Silmar
