### ISSUE TITLE
No compartilhamento adicionar a url do episódio

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#49]
No compartilhamento ainda falta adicionar a url do episódio.
(facebook, twitter)

**Comment by diegofrutuoso** [comment]
Será tratado juntamente com a issue https://github.com/CloudRadioProject/BugReport/issues/24

**Comment by lczanatta** [comment]
Isaura 101

Em 9 de fev de 2017 11:14, "diegofrutuoso" <notifications@github.com>
escreveu:
