### ISSUE TITLE
Velocidade do menu hamburguer

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#5]
Hamburger Menu apresenta o Texto completo antes da expansão do frame.

**Comment by lczanatta** [comment]
verificar com o silmar a possibilidade de não ter o menu lateral expandindo. e ter a descrição dos botões a baixo

**Comment by silmargeremia** [comment]
Não é possível por causa da forma como as playlists vão ser implementadas. Veja as issues sobre playlists.

**Comment by silmargeremia** [comment]
Procure ver como o menu hambúrguer do Google play music funciona.

**Comment by diegofrutuoso** [comment]
Velocidade corrigida pelo @AlanBessa
