### ISSUE TITLE
Player não funciona no mobile

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#50]
Player continua não funcionando no Chrome mobile (android/iOS).
reprodução fica parada.

![screen shot 2016-12-17 at 13 52 43](https://cloud.githubusercontent.com/assets/18125774/21288055/1ce57d8c-c460-11e6-8b42-06185b5f750f.png)

**Comment by diegofrutuoso** [comment]
Será tratado juntamente com a issue https://github.com/CloudRadioProject/BugReport/issues/13
