### ISSUE TITLE
compartilhamento no player

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#53]
Separar um pouco os botões de compartilhamento Face, Twitter
![screen shot 2016-12-17 at 13 56 58](https://cloud.githubusercontent.com/assets/18125774/21288070/c9e9f9ae-c460-11e6-8aa6-cf5d3f54f312.png)

**Comment by diegofrutuoso** [comment]
Será tratado na issue https://github.com/CloudRadioProject/BugReport/issues/24
