### ISSUE TITLE
Mudanças organizacionais menu hamburguer esquerdo

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#58]
Remover o avatar do usuário desta parte do sistema, assim como as funcionalidade "perfil" e "sair" proximos a ele.

Primeiro botão/função do menu passa a ser o Home

![screen shot 2016-12-17 at 15 58 27](https://cloud.githubusercontent.com/assets/18125774/21288749/ec18f096-c471-11e6-8ba3-7a688e929f38.png)

**Comment by lczanatta** [comment]
ajustado como pedido. fechando junto com a issue 57
