### ISSUE TITLE
Importação e sincronização de mensagens

### ISSUE THREAD

**Issue by nanaka-gouvea** [CloudRadioProject/BugReport#61]
Na página do episódio Contrafactual 2, do scicast, fiz um comentário, mas ele não aparece no site wordpress (portal deviante). E os comentários do site não aparecem no CloudRadio. Não deveria ser sincronizado?

**Comment by silmargeremia** [comment]
Esse problema foi realmente um bug que encontramos na forma como o o Disqus identifica o post para integrar os comentários. Já foi corrigido diretamente no post do contrafactual.
