### ISSUE TITLE
Corte no Player

### ISSUE THREAD

**Issue by napalmsp** [CloudRadioProject/BugReport#66]
- Entrei e iniciei o audio de um podcast.
- entrei no em outro episódio do mesmo podcast enquanto ouvia o audio do primeiro
- cliquei na arte da capa e com isso ele cortou o audio e fiquei perdido pra retornar o player.

Recomendação, ao clicar nas image, abrir em um modal flutuante.

**Comment by malforea** [comment]
Apesar de ser informado o tamanho mínimo para a foto de capa da estação, ainda não consegui descobrir qual o tamanho exato para uma boa. Qual o tamanho ideal para uma capa de estação?

Também o recurso de corte e adaptação após o carregamento da imagem não está funcionando.

**Comment by diegofrutuoso** [comment]
Boa tarde.
Foi corrigido esse problema em produção. Muito obrigado por avisar.
