### ISSUE TITLE
Ver quantos seguidores tenho

### ISSUE THREAD

**Issue by caiohansen** [CloudRadioProject/BugReport#67]
Não aparece o número de seguidores que tenho no meu próprio perfil. Só consigo ver o dos outros e os outros conseguem ver o meu.

**Comment by lczanatta** [comment]
Desculpa, Caio. Ainda vamos adicionar esse dado para vocês terem acesso. Não deve demorar muito, provavelmente deve estar no próximo release.
Muito obrigado pelo feedback.

**Comment by lczanatta** [comment]
Agora o usuário conseguira ver o número de seguidores em próprio perfil!
