### ISSUE TITLE
Não é possível remover episodio que foram baixados

### ISSUE THREAD

**Issue by maisonChaves** [CloudRadioProject/BugReport#69]
* Mobile 
* Celular Moto X Play 

Depois de ter os episodios baixados no celular não consigo remove-los ocasionando uso escessivo de armazenamento interno do aparelho. 

O mesmo acontece com os episodios na playlist.

**Comment by diegofrutuoso** [comment]
Olá @maisonChaves , tudo bom?

Para remover, basta ir na seção de downloads, passar deu dedo sobre o nome do episódio da direita para a esquerda e o botãod e remover irá aparecer.
Estamos trabalhando em um tutorial na primeira vez que o usuário instala o app, para sanar esses problema de UX por hora.

**Comment by diegofrutuoso** [comment]
Vou fechar esse card, qualquer dúvida você pode reabri-lo tudo bem?
