### ISSUE TITLE
Controle remotos no player do app

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#74]
Tela: Player do App Android

Descrição: Controles remotos
Incluir opção para que o aplicativo reaja a controles enviados de headset e outros.
Muito útil, especialmente quando usa o fone de ouvido padrão do celular, utilizar o botão de liga/desliga para pausar/continuar o episódio.

Pessoa que enviou: tgmspawn@gmail.com

**Comment by felipeprov** [comment]
Pause e resume já estão funcionais,
assim como desconectar o fone, preciso cavar um pouco mais para  ver se a api suporta mais eventos

**Comment by felipeprov** [comment]
Passando a utilizar a MediaBrowser e MediaService para tratar comandos de media padrão.
Headset Buttons devem estar funcionais agora.
