### ISSUE TITLE
Teclado não some depois da pesquisa

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#75]
Tela: Pesquisa

Descrição: Não exatamente um erro... o digitar algo no campo de pesquisa, no telefone, o teclado continua aparecendo depois de clicar em "pesquisar". O teclado podia se recolher depois disso.

Pessoa que enviou: Não se identificou

**Comment by felipeprov** [comment]
Teclado virtual é escondido após submeter a query
