### ISSUE TITLE
Possibilidade de visualizar pessoas que assinaram

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#77]
Tela: Página da minha estação

Descrição: Não é possível visualizar quais pessoas assinaram a estação.

Pessoa que enviou: marcelocafiero@gmail.com

**Comment by diegofrutuoso** [comment]
@silmargeremia Essa é uma feature que por hora não temos prevista, dada a sensibilidade dos dados dos usuarios isso é algo que seria liberado?

**Comment by silmargeremia** [comment]
Não, isso provavelmente nunca será permitido.

**Comment by diegofrutuoso** [comment]
Fechando essa issue devido a sensibilidade dos dados que seriam expostos.
