### ISSUE TITLE
Ouvir online não funciona

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#79]
Tela: Aplicativo

Descritição: O botão para ouvir online não responde. Funcionou uma vez no começo, mas desde então ele não tem respondido. O símbolo de + e - ao lado também não é nada intuitivo

Pessoa que enviou: Não informou

**Comment by felipeprov** [comment]
Toda a parte de streaming foi alterada para a versão 0.0.12.
Estamos passando a explorar muito mais as funcionalidades nativas, espero que eventuais problemas com o streaming seja resolvido com isso.
