### ISSUE TITLE
Reproduz vários áudios simultâneos

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#8]
"Ao clicar no play de um episódio e, logo em seguida, em outro episódio nessa mesma página, o audio do primeiro continua tocando fazendo com que fiquem os dois audios ao mesmo tempo.
 
 Se clicar rapidamente em um terceiro, ficam os três tocando. Como o player na parte inferior é único, mesmo pausando os outros que começaram a ser reproduzido continuam. A única forma de parar é recarregando a página.
 
 Pelo que percebi, isso não acontece se esperar um tempo entre um clique e outro (a partir de 5 segundos). Mas não é preciso ser muito rápido para o bug aparecer... Clicando em um e depois no outro em um segundo por exemplo, já causa o bug.
 
 Usando Firefox e Chromium para Ubuntu 16.04 LTS 32 bits"

**Comment by diegofrutuoso** [comment]
@lczanatta Pode validar se o erro ainda acontece?
Lembro de termos corrigido.

Obrigado.

**Comment by lczanatta** [comment]
@diegofrutuoso o problema ainda existe no firefox. Quando se da um play, tem que verificar se exite algo tocando e parar ele. ou desabilitar o botão de play por um curto período de tempo

**Comment by lczanatta** [comment]
@diegofrutuoso  Ajuste realizado.
