### ISSUE TITLE
Tela desliza ao tentar avançar o tempo do episódio

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#80]
Tela: Reprodução de episódio (App Android)

Descrição: Ao tentar deslizar o botão da barra de reprodução para avançar o tempo, a tela desliza junto. O erro pode ser contornado deslizando a partir de um ponto na barra que não seja o botão. Mas como o botão é mais intuitivo, achei que valia a pena reportar o erro.

Pessoa que enviou:  Não informou

**Comment by felipeprov** [comment]
Propagação de eventos desabilitada na área do slider,
Resolvido
