### ISSUE TITLE
Episódio com problemas para ouvir

### ISSUE THREAD

**Issue by diegofrutuoso** [CloudRadioProject/BugReport#83]
Tela: APP ANDROID

Descrição: passei o fim de semana usando o App android, e raramente dava para ouvir um episódio até o fim. tive que voltar varias vezes para ouvir até o fim.

Pessoa que enviou: Não informou.

**Comment by diegofrutuoso** [comment]
Comentário do Diego:

Tive problema similar com MOTO G3.
As vezes ele para e não é possível retomar sem ir  de novo no app, entrar nos download, e escolher o episódio novamente.

**Comment by felipeprov** [comment]
Isso se deve ao android matando o processo em background.
A nova versão passa a utilizar um serviço para implementar o player, dessa forma podemos mante-lo ativo, mesmo que a interface seja morta pelo OS.
