### ISSUE TITLE
Bug no recurso estações agregadas

### ISSUE THREAD

**Issue by silmargeremia** [CloudRadioProject/BugReport#88]
![screenshot_20170106-164827](https://cloud.githubusercontent.com/assets/18125774/21729173/fb639e2e-d430-11e6-8fb6-cfbacb3f9a9d.png)
![img-20170106-wa0010](https://cloud.githubusercontent.com/assets/18125774/21729178/04ae6c20-d431-11e6-8cd9-5525ba631265.jpg)

Recurso de estações agregadas listando. Nomes em branco. Ao tentar salvar as alterações, gera o erro dá imagem.

**Comment by lczanatta** [comment]
Ajuste realizado
