### ISSUE TITLE
Problema na página de inscrições

### ISSUE THREAD

**Issue by victorhugosilvaspbr** [CloudRadioProject/BugReport#99]
Quando abro a página de inscrições (http://www.cloudradio.com.br/inscricoes), é exibido um erro, mas sem esclarecimento do qual seria, e a lista de inscrições não é carregada. Segue captura de tela:

![2017-01-28](https://cloud.githubusercontent.com/assets/24967470/22399673/10270d6e-e589-11e6-9ed6-1cefe8373eb2.png)

Erro semelhante acontece na versão para Android, a lista de inscrições não é carregada, mesmo quando eu arrasto para baixo para atualizar. Segue a captura:

![screenshot_20170128-183022](https://cloud.githubusercontent.com/assets/24967470/22399682/701830ae-e589-11e6-9b63-cc47825eff9c.png)

**Comment by lsfranco** [comment]
Pelo console vi que o erro é gerado ao não conseguir carregar a url:
http://67.205.137.40:8080/activityFromUser/follow/user?populateUsers=true
Esse cara tá retornando um 500.

**Comment by victorhugosilvaspbr** [comment]
Por "esse cara", você diz o meu usuário, ou a página?

**Comment by diegofrutuoso** [comment]
Bug corrigido em produção.
Muito obrigado pelo aviso. 👍
